"use strict";

/*
==========================================================
WealthBuilder OS

DNA Route

Version : 2.0.0
Status  : Production
Atlas Certification : Pending

Purpose
-------
Provides trader DNA analysis generated by the
DNA Engine.

Responsibilities
----------------
✓ Trading DNA Analysis
✓ Structured Responses
✓ Structured Logging
✓ Health Endpoint
✓ Version Endpoint

Business logic belongs exclusively to
dnaEngine.

==========================================================
*/

const express = require("express");

const router = express.Router();

const logger = require("../services/logger");

const dnaEngine =
    require("../services/dnaEngine");

/*
==========================================================
Response Helpers
==========================================================
*/

function sendSuccess(
    res,
    data,
    message = "Success"
) {

    return res.json({

        success: true,

        message,

        data

    });

}

function sendError(
    res,
    status,
    error
) {

    return res.status(status).json({

        success: false,

        error

    });

}

/*
==========================================================
GET /
==========================================================
*/

router.get("/", (req, res) => {

    try {

        logger.info(

            logger.SOURCES.DNA,

            "DNA analysis requested."

        );

        const report =
            dnaEngine.analyse();

        logger.info(

            logger.SOURCES.DNA,

            "DNA analysis completed."

        );

        return sendSuccess(

            res,

            report,

            "DNA analysis completed."

        );

    }

    catch (error) {

        logger.error(

            logger.SOURCES.DNA,

            "DNA analysis failed.",

            {

                error: error.message

            }

        );

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /health
==========================================================
*/

router.get("/health", (req, res) => {

    try {

        const health =

            dnaEngine.getHealth
                ? dnaEngine.getHealth()
                : {

                    service: "dna",

                    status: "READY"

                };

        return sendSuccess(

            res,

            health,

            "DNA service healthy."

        );

    }

    catch (error) {

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /version
==========================================================
*/

router.get("/version", (req, res) => {

    return sendSuccess(

        res,

        {

            version:

                dnaEngine.getVersion
                    ? dnaEngine.getVersion()
                    : "2.0.0"

        },

        "DNA Service Version"

    );

});

/*
==========================================================
Export
==========================================================
*/

module.exports = router;
