"use strict";

/*
==========================================================
WealthBuilder OS

Logs Route

Version : 2.0.0
Status  : Production
Atlas Certification : Pending

Purpose
-------
Provides access to application logs generated by
the certified Logger Service.

Responsibilities
----------------
✓ Log Retrieval
✓ Structured Responses
✓ Structured Logging
✓ Health Endpoint
✓ Version Endpoint

Business logic belongs exclusively to
logger.js.

==========================================================
*/

const express = require("express");

const router = express.Router();

const logger = require("../services/logger");

/*
==========================================================
Response Helpers
==========================================================
*/

function sendSuccess(
    res,
    data,
    message = "Success"
) {

    return res.json({

        success: true,

        message,

        data

    });

}

function sendError(
    res,
    status,
    error
) {

    return res.status(status).json({

        success: false,

        error

    });

}

/*
==========================================================
GET /
==========================================================
*/

router.get("/", (req, res) => {

    try {

        logger.info(

            logger.SOURCES.SYSTEM,

            "Log retrieval requested."

        );

        const logs = logger.getLogs();

        logger.info(

            logger.SOURCES.SYSTEM,

            "Log retrieval completed.",

            {

                logCount: Array.isArray(logs)
                    ? logs.length
                    : 0

            }

        );

        return sendSuccess(

            res,

            logs,

            "Logs retrieved successfully."

        );

    }

    catch (error) {

        logger.error(

            logger.SOURCES.SYSTEM,

            "Log retrieval failed.",

            {

                error: error.message

            }

        );

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /health
==========================================================
*/

router.get("/health", (req, res) => {

    try {

        const health =

            logger.getHealth
                ? logger.getHealth()
                : {

                    service: "logs",

                    status: "READY"

                };

        return sendSuccess(

            res,

            health,

            "Logs service healthy."

        );

    }

    catch (error) {

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /version
==========================================================
*/

router.get("/version", (req, res) => {

    return sendSuccess(

        res,

        {

            version:

                logger.getVersion
                    ? logger.getVersion()
                    : "2.0.0"

        },

        "Logs Service Version"

    );

});

/*
==========================================================
Export
==========================================================
*/

module.exports = router;
