"use strict";

/*
==========================================================
WealthBuilder OS

Morning Brief Route

Version : 2.0.0
Status  : Production
Atlas Certification : Pending

Purpose
-------
Provides the daily Morning Brief generated by the
Morning Brief Service.

Responsibilities
----------------
✓ Morning Brief Generation
✓ Structured Responses
✓ Structured Logging
✓ Health Endpoint
✓ Version Endpoint

Business logic belongs exclusively to
morningBriefService.

==========================================================
*/

const express = require("express");

const router = express.Router();

const logger = require("../services/logger");

const morningBriefService =
    require("../services/morningBrief");

/*
==========================================================
Response Helpers
==========================================================
*/

function sendSuccess(
    res,
    data,
    message = "Success"
) {

    return res.json({

        success: true,

        message,

        data

    });

}

function sendError(
    res,
    status,
    error
) {

    return res.status(status).json({

        success: false,

        error

    });

}

/*
==========================================================
GET /
==========================================================
*/

router.get("/", async (req, res) => {

    try {

        logger.info(

            logger.SOURCES.MORNING_BRIEF,

            "Morning Brief requested."

        );

        const report =
            await morningBriefService.generate();

        logger.info(

            logger.SOURCES.MORNING_BRIEF,

            "Morning Brief generated successfully."

        );

        return sendSuccess(

            res,

            report,

            "Morning Brief generated."

        );

    }

    catch (error) {

        logger.error(

            logger.SOURCES.MORNING_BRIEF,

            "Morning Brief generation failed.",

            {

                error: error.message

            }

        );

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /health
==========================================================
*/

router.get("/health", (req, res) => {

    try {

        const health =

            morningBriefService.getHealth
                ? morningBriefService.getHealth()
                : {

                    service: "morning-brief",

                    status: "READY"

                };

        return sendSuccess(

            res,

            health,

            "Morning Brief service healthy."

        );

    }

    catch (error) {

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /version
==========================================================
*/

router.get("/version", (req, res) => {

    return sendSuccess(

        res,

        {

            version:

                morningBriefService.getVersion
                    ? morningBriefService.getVersion()
                    : "2.0.0"

        },

        "Morning Brief Service Version"

    );

});

/*
==========================================================
Export
==========================================================
*/

module.exports = router;
