"use strict";

/*
==========================================================
WealthBuilder OS

Psychology Route

Version : 2.0.0
Status  : Production
Atlas Certification : Pending

Purpose
-------
Provides trader psychology analysis generated by
the Psychology Engine.

Responsibilities
----------------
✓ Psychology Analysis
✓ Structured Responses
✓ Structured Logging
✓ Health Endpoint
✓ Version Endpoint

Business logic belongs exclusively to
psychologyEngine.

==========================================================
*/

const express = require("express");

const router = express.Router();

const logger = require("../services/logger");

const psychologyEngine =
    require("../services/psychologyEngine");

/*
==========================================================
Response Helpers
==========================================================
*/

function sendSuccess(
    res,
    data,
    message = "Success"
) {

    return res.json({

        success: true,

        message,

        data

    });

}

function sendError(
    res,
    status,
    error
) {

    return res.status(status).json({

        success: false,

        error

    });

}

/*
==========================================================
GET /
==========================================================
*/

router.get("/", (req, res) => {

    try {

        logger.info(

            logger.SOURCES.PSYCHOLOGY,

            "Psychology analysis requested."

        );

        const report =
            psychologyEngine.analyse();

        logger.info(

            logger.SOURCES.PSYCHOLOGY,

            "Psychology analysis completed."

        );

        return sendSuccess(

            res,

            report,

            "Psychology analysis completed."

        );

    }

    catch (error) {

        logger.error(

            logger.SOURCES.PSYCHOLOGY,

            "Psychology analysis failed.",

            {

                error: error.message

            }

        );

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /health
==========================================================
*/

router.get("/health", (req, res) => {

    try {

        const health =

            psychologyEngine.getHealth
                ? psychologyEngine.getHealth()
                : {

                    service: "psychology",

                    status: "READY"

                };

        return sendSuccess(

            res,

            health,

            "Psychology service healthy."

        );

    }

    catch (error) {

        return sendError(

            res,

            500,

            error.message

        );

    }

});

/*
==========================================================
GET /version
==========================================================
*/

router.get("/version", (req, res) => {

    return sendSuccess(

        res,

        {

            version:

                psychologyEngine.getVersion
                    ? psychologyEngine.getVersion()
                    : "2.0.0"

        },

        "Psychology Service Version"

    );

});

/*
==========================================================
Export
==========================================================
*/

module.exports = router;
